### PR TITLE
Add Open in Kaggle badge

### PR DESCRIPTION
**Pull request by pizzaz93**
This is an example of what adding a Kaggle Badge (that allows for opening the .ipynb as a Kaggle Notebook as seen here https://www.kaggle.com/product-feedback/152480) could look like.

If it makes sense I can submit a further PR adding it to the other notebooks in this repository.

### CODE REVIEW

**Comment by ageron** [comment]
Hi @pizzaz93 ,
Thanks a lot for this suggestion, I love it! If you want to send a PR for all the other notebooks as well, that would be greatly appreciated. Note that many notebooks check whether they are running on Colab, and if so they download datasets or images, or they install some libraries. In the first cells, they try to `import google.colab`, and if this succeeds, they define `IS_COLAB=True` and run the appropriate installation/downloading steps. We would need the same thing for Kaggle. I'm not sure what libs are preinstalled on Kaggle kernels, so it would be good to test that everything works smoothly.
If you don't have time to do all this, no worries, you can just add the `Open in Kaggle` links, and I'll take care of the rest.
Thanks again!

**Comment by pizzaz93** [comment]
Hi @ageron,
I can definitely add the `Open in Kaggle` badges to the other notebooks as further commits in this PR. The other aspects of ensuring the notebooks run smoothly on Kaggle I wouldn't be able to do, but if you run into any issues or have any questions feel free to ping me.
Peretz

**Comment by ageron** [comment]
Awesome, thanks for your help Peretz!

**Comment by ageron** [comment]
I just updated all the notebooks so they run nicely on Kaggle. Please make sure you `git pull` before you add the "Open in Kaggle" links. I'll add Kaggle to the README.md as well.

**Comment by pizzaz93** [comment]
Perfect, that's great, I'll make sure to do so.

**Comment by ageron** [comment]
One thing I'm struggling with is the index.ipynb notebook, which is just a table of contents that points to the other notebooks. It contains relative links, and these work fine in Colab and Binder, but not in Kaggle or DeepNote. I'm not sure how to fix this, other than putting an "open in kaggle" link next to each notebook, which wouldn't look great. Any ideas?

**Comment by pizzaz93** [comment]
Based on the way that Kaggle is currently built the best available solution I was given was to create and save those notebooks as Kaggle Notebooks and then to link to them, which I understand would add a maintenance overhead.

**Comment by pizzaz93** [comment]
I've added links to all the notebooks besides (2 and 8, 9, 14, 15, 17) and tested their links.

My branch is up to date with the edit you made today as well.

**Comment by ageron** [comment]
Very cool, thanks! However, could you please do a search & replace for pizzaz93 => ageron to ensure that the links remain in the same repo?

**Comment by pizzaz93** [comment]
Good catch, I apologize for that, I'll fix it tomorrow morning.

**Comment by pizzaz93** [comment]
All the links have been updated to point to the ipynbs in the original repo.

**Comment by ageron** [comment]
Thanks again @pizzaz93 , that's great! 👍

**Pull request merged**
