### PR TITLE
Chapter 17 Question 10 and 11 - possible solution contributions

### PR DESCRIPTION
**Pull request by KirkDCO**
I've included my solution to Chapter 17 Question 10 in which I build a simple VAE for an RGB image dataset of flowers.  The generated flowers aren't as good as I had hoped, but I think there are some interesting results.

The original version of this can be found here:  https://github.com/KirkDCO/HandsOnML_Exercises/blob/main/Ch17_Q10.ipynb

In that version, I also train a standard Convolutional Autoencoder and look at reconstructions of images.  I left that portion out for brevity and not to distract from the VAE aspect.  I would like to take this extended version and create a Kaggle notebook to share, as long as that is OK.  I don't want to create any conflict of interest between content of this notebook and one on Kaggle with much the same content.

I appreciate any comments on code.  I don't expect you to fix any errors and I respect your option to decline this PR if the results aren't good enough.

I may work on this more in the future, and if I come up with enhancements, I'm happy to share those.  

I will likely use the same dataset to develop a GAN for Question 1.  Once I have some interesting results, I'm happy to share/contribute that code as well.

### CODE REVIEW

**Comment by ageron** [comment]
Hi @KirkDCO ,
Thanks a lot for the PR! Really appreciate your help. I haven't had time to look into it yet, I'll try to do this early next week.

**Comment by KirkDCO** [comment]
No hurry whatsoever!  I'm still toying with it a bit to try and improve the fake flower images, but haven't been able to improve upon it yet.  I will probably start working on Question 11 and application of a DCGAN to the same dataset soon.

**Comment by KirkDCO** [comment]
I modified my VAE to have a dramatically reduced coding layer size.  The results are much better, but still not quite flower like.  Regardless, I'm hopeful it demonstrates a useful VAE on a different dataset.

**Comment by KirkDCO** [comment]
I just added a candidate solution for Q11 in which I work through a DCGAN.  Again, images won't fool anyone, but it is a working version.

**Comment by ageron** [comment]
Hi @KirkDCO,
Thanks again for your contribution, I finally had some time to look at it today, you spent quite some time on this, I really appreciate it.

Here are a few comments regarding the VAE:

* I like the description of your tests and the difficulties you ran across, but I'd like to keep the solutions fairly tutorial-like. I suggest you could have the full notebook in your github repo, which this notebook could point to for the readers who want the full details (and attribution to you), and in this repo we could shorten the solution to keep only the second try, which looks much better. Would that work for you?
* There are many images, which more than doubles the size of the notebook (from 6.3M to 13M). I'm trying to limit the size of the repo, so it would be great to output only a few images.
* The flowers dataset is already introduced in chapter 14, so it would be best to load it in the same way. It would be simpler than requiring the user to download it on their Google Drive, and it would work on local Jupyter, not just Colab.

What do you think?

**Comment by KirkDCO** [comment]
I adjusted Q10 to use the TensorFlow Flowers dataset, but the results are much, much worse.  There is always the chance that I've broken something in the process, but in working with it, I cannot seem to improve the performance.

I will continue to work on it, but I may cancel the PR as these results are not really worth including, in my opinion.

**Comment by KirkDCO** [comment]
Q11 was adjusted to use tf flowers dataset.  GAN results are much poorer with this dataset, despite a lot of effort on tuning.

Happy to defer to your judgement to keep/reject either submission.

**Pull request closed without merging**
