### PR TITLE
Squash layers for pip install (dockerfile best practice)

### PR DESCRIPTION
**Pull request by patsancu**
It's a best practice (recommended on the docker website) to squash layers / minimize number of layers on Dockerfiles

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers

### CODE REVIEW

**Comment by ageron** [comment]
Thanks @patsancu ,
Looks good to me, but why do we install tf-nightly-2.0-preview and then uninstall tensorflow? Perhaps it would be best to install tensorflow-2.0.0-rc1 instead?
Wdyt?

**Comment by patsancu** [comment]
Hi @ageron 
What you say looks fine to me, but my PR was mainly based on squashing docker layers, not on the actual contents of the pip install :)

To test your assumptions, I would need a lot more time, since your book is so popular (even I bought it) that it should be thoroughly tested

**Comment by ageron** [comment]
I see, thanks for your feedback. 👍

**Comment by eriktrom** [comment]
@patsancu - https://github.com/ageron/handson-ml2/pull/33 adds to this, python package management is something i need to work on but outside of the peer dep warnings i tmp fixed, I did the heavy lifting of f'ing with docker more, if u want to improve on it, your welcome too, fyi

**Comment by patsancu** [comment]
@eriktrom your PR (#33 ) looks nice! but I couldn't help with it
The only thing I'm doing in this PR is squashing pip install layers, which wouldn't be even needed in the case ageron accepted your PR (since you install dependencies with `pip install -r requirements.txt` )

As you say, the python dependencies looks weird, but  IMO it's very hard to test that any given dependency change/version will not break any notebook

Wish you the best fixing them :)

**Pull request closed without merging**
